FROM metacell/scidash_virgo_base:latest

ARG APP_DIR=/app
ARG SOURCES_DIR=$APP_DIR/sources
ARG VIRGO_DIR=/opt/virgo
ARG SCIDASH_REPO_FOLDER=/git
ARG GEPPETTO_REPO=http://github.com/openworm/org.geppetto.git
ARG SCIDASH_BRANCH=geppetto-scidash

ARG targetBranch=geppetto-scidash
ARG originBranch=geppetto-scidash
ARG defaultBranch=geppetto-scidash

ENV HOME /home/developer

# -== Create various folder for this deployment ==-
WORKDIR $SCIDASH_REPO_FOLDER
# -== get the latest travis_utils ==-
RUN rm -rf travis_utils
RUN git clone https://github.com/ddelpiano/travis_utils
RUN cp travis_utils/copy.sh $APP_DIR

# -== Download SCIDASH repo ==-
RUN rm -rf scidash
RUN $APP_DIR/copy.sh https://github.com/Metacell/scidash.git "${targetBranch}" "${originBranch}" "${defaultBranch}"

# -== INSTALL GEPPETTO ==-
WORKDIR $SOURCES_DIR
RUN $APP_DIR/copy.sh http://github.com/openworm/org.geppetto.git "${targetBranch}" "${originBranch}" "${defaultBranch}"
RUN cp /git/scidash/service/geppetto/config.json $SOURCES_DIR/org.geppetto/utilities/source_setup
RUN cp /git/scidash/service/geppetto/setup.py $SOURCES_DIR/org.geppetto/utilities/source_setup
RUN cp /git/scidash/service/geppetto/geppetto.plan $SOURCES_DIR/org.geppetto/

RUN $APP_DIR/copy.sh https://github.com/openworm/org.geppetto.model.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.model &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.model\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

RUN $APP_DIR/copy.sh https://github.com/openworm/org.geppetto.core.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.core && cp /git/scidash/service/geppetto/core/app-config.xml ./src/main/java/META-INF/spring &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.core\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

RUN $APP_DIR/copy.sh https://github.com/openworm/org.geppetto.model.neuroml.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.model.neuroml &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.model.neuroml\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

RUN $APP_DIR/copy.sh https://github.com/openworm/org.geppetto.simulation.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.simulation &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.simulation\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

RUN $APP_DIR/copy.sh https://github.com/openworm/org.geppetto.simulator.external.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.simulator.external &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.simulator.external\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

RUN $APP_DIR/copy.sh https://github.com/Metacell/org.geppetto.simulator.scidash.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.simulator.scidash &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.simulator.scidash\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

RUN $APP_DIR/copy.sh https://github.com/openworm/org.geppetto.frontend.git "${targetBranch}" "${originBranch}" "${defaultBranch}" &&\
    cd org.geppetto.frontend && cp /git/scidash/service/geppetto/frontend/app-config.xml ./src/main/webapp/WEB-INF/spring/ &&\
    /bin/echo -e "\e[96mMaven install org.geppetto.frontend\e[0m" &&\
    mvn -Dhttps.protocols=TLSv1.2 -DskipTests --quiet install &&\
    rm -rf src && cd ../

WORKDIR $SOURCES_DIR/org.geppetto/utilities/source_setup
RUN python2 update_server.py

WORKDIR $APP_DIR

RUN chown developer $VIRGO_DIR

# -== Clean up to reduce container size ==-
RUN rm -rf $SCIDASH_REPO_FOLDER
RUN rm -rf /tmp/virgo.zip /tmp/apache-maven-3.5.2-bin.tar.gz
USER developer

EXPOSE 8080
CMD /opt/virgo/bin/startup.sh
