FROM python:3.6

ARG APP_DIR=/app
ARG SOURCES_DIR=$APP_DIR/sources
ARG VIRGO_DIR=/opt/virgo
ARG SCIDASH_REPO_FOLDER=/git
ARG GEPPETTO_REPO=http://github.com/openworm/org.geppetto.git
ARG SCIDASH_BRANCH=geppetto-scidash

ARG targetBranch=geppetto-scidash
ARG originBranch=geppetto-scidash
ARG defaultBranch=geppetto-scidash

ENV HOME /home/developer

# -== Create various folder for this deployment ==-
RUN mkdir $APP_DIR
RUN mkdir $SCIDASH_REPO_FOLDER
WORKDIR $APP_DIR
RUN mkdir $SOURCES_DIR
WORKDIR $SCIDASH_REPO_FOLDER
RUN git clone https://github.com/ddelpiano/travis_utils
RUN cp travis_utils/copy.sh $APP_DIR

# -== Download SCIDASH repo ==-
RUN $APP_DIR/copy.sh https://github.com/Metacell/scidash.git "${targetBranch}" "${originBranch}" "${defaultBranch}"

# -== Install OpenJDK and certificates ==-
WORKDIR /
RUN useradd -ms /bin/bash developer
ENV HOME /home/developer
RUN printf "\ndeb http://deb.debian.org/debian/ sid main\n" >> /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# -== Setup JAVA_HOME ==-
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

# -== INSTALL MAVEN ==-
WORKDIR /tmp
RUN wget http://archive.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
RUN tar xzf apache-maven-3.5.2-bin.tar.gz -C /opt/
RUN ln -s /opt/apache-maven-3.5.2 /opt/maven
RUN ln -s /opt/maven/bin/mvn /usr/local/bin
RUN rm -f /apache-maven-3.5.2-bin.tar.gz
ENV MAVEN_HOME /opt/maven
RUN mvn --version

# -== INSTALL NEURON ==-
RUN mkdir /nrn
WORKDIR /nrn
RUN apt-get install -y libreadline5 libreadline-gplv2-dev lsof
RUN wget -O nrn-7.6.tar.gz https://github.com/ddelpiano/neuron/raw/master/nrn-7.6.tar.gz
RUN tar xzvf nrn-7.6.tar.gz
WORKDIR nrn-7.6
RUN ./configure \
    --without-x \
    --with-nrnpython=python3 \
    --without-paranrn \
    --prefix=`pwd` \
    --without-iv \
    --without-nrnoc-x11 \
    --silent &&\
make --silent -j4 &&\
make --silent install -j4
WORKDIR src/nrnpython
ENV NEURON_HOME /nrn/nrn-7.6/x86_64/bin
RUN python setup.py install

# -== Linking Neuron environment with application and geppetto ==-
RUN mkdir -p /Applications/NEURON-7.6/
WORKDIR /Applications/NEURON-7.6/
RUN ln -s /nrn/nrn-7.6 nrn
WORKDIR /usr/local
RUN ln -s /nrn/nrn-7.6 nrn
RUN chown developer nrn
RUN ls -l /usr/local/nrn/

# -== INSTALL VIRGO ==-
RUN mkdir $VIRGO_DIR
RUN apt-get -y install curl
RUN curl -L 'http://www.eclipse.org/downloads/download.php?file=/virgo/release/VP/3.7.2.RELEASE/virgo-tomcat-server-3.7.2.RELEASE.zip&r=1' > virgo.zip
RUN unzip virgo.zip
RUN cp -r ./virgo-tomcat-server-3.7.2.RELEASE/* $VIRGO_DIR
RUN rm $VIRGO_DIR/configuration/java-server.profile
RUN cp /git/scidash/service/geppetto/java-server.profile $VIRGO_DIR/configuration/
RUN rm $VIRGO_DIR/configuration/tomcat-server.xml
RUN cat /git/scidash/service/geppetto/tomcat-server.xml | sed 's/127.0.0.1/0.0.0.0/' > $VIRGO_DIR/configuration/tomcat-server.xml
RUN chmod u+x $VIRGO_DIR/bin/*.sh
ENV SERVER_HOME $VIRGO_DIR
RUN chmod 777 -R $VIRGO_DIR
RUN mkdir $VIRGO_DIR/repository/usr
RUN mvn --version
